---

- include_tasks: context.yml

- block:

    - include_tasks: setup_linux.yml
      when: ansible_system == "Linux"

  when: want_teamviewer

- name: set has_teamviewer
  set_fact:
    has_teamviewer: "{{ want_teamviewer }}"
