---

- include_tasks: context.yml

- block:
    - include_tasks: setup_prereq.yml

    - include_tasks: setup_linux_apt.yml
      when: ansible_pkg_mgr == 'apt'

    - include_tasks: setup_linux.yml
      when:
        - ansible_system == "Linux"
        - ansible_pkg_mgr != 'apt'

    - include_tasks: service.yml

  when: want_teamviewer

- name: set has_teamviewer
  set_fact:
    has_teamviewer: "{{ want_teamviewer }}"
