---

- name: check installed
  command:
    cmd: "which {{ teamviewer_bin }}"
  changed_when: no
  failed_when: no
  register: t_teamviewer_which


- block:
    - name: select package
      set_fact:
        teamviewer_package: "{{ teamviewer_package[ansible_distribution] | default(teamviewer_package[ansible_system]) }}"

    - name: set package url
      set_fact:
        teamviewer_package_url: "{{ teamviewer_base_url }}{{ teamviewer_package }}"

    - name: download teamviewer package
      get_url:
        url: "{{ teamviewer_package_url }}"
        dest: "/tmp/{{ teamviewer_package }}"
        mode: "0644"

    - name: install teamviewer
      command:
        cmd: "dpkg -i /tmp/{{ teamviewer_package }}"
      when: teamviewer_package.endswith('.deb')

    - name: clean downloaded
      file:
        path: "/tmp/{{ teamviewer_package }}"
        state: absent

  when: t_teamviewer_which.rc != 0


- name: enable / start
  systemd:
    name: "{{ teamviewer_service }}.service"
    enabled: true
    state: started
  when: want_teamviewer_started

- name: disable / stop
  systemd:
    name: "{{ teamviewer_service }}.service"
    enabled: false
    state: stopped
  when: not want_teamviewer_started
